name: Build APK and Create Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' 
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Get version using git-semver
      id: version
      run: |
        VERSION=${{ steps.gitversion.outputs.semVer }}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Build APK in debug mode
      run: ./gradlew assembleDebug

    - name: Archive APK and metadata
      run: |
        mkdir -p build-artifacts
        cp app/build/outputs/apk/debug/app-debug.apk build-artifacts/app-debug.apk
        echo "Version: $VERSION" > build-artifacts/version.txt
        echo "Git Commit: $(git rev-parse HEAD)" >> build-artifacts/version.txt
        echo "Build Time: $(date)" >> build-artifacts/version.txt

    - name: Upload APK and metadata as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build-artifacts

    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${{ env.VERSION }}
        RELEASE_NAME="Release $VERSION"
        CHANGELOG="Automatic release based on version $VERSION"

        # Create the release
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"tag_name\":\"$VERSION\",\"name\":\"$RELEASE_NAME\",\"body\":\"$CHANGELOG\"}" \
          https://api.github.com/repos/${{ github.repository }}/releases

    - name: Upload artifacts to the release
      run: |
        VERSION=${{ env.VERSION }}
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/tags/$VERSION | jq -r .id)
        echo "Release ID: $RELEASE_ID"

        # Upload APK
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -F "file=@build-artifacts/app-debug.apk" \
          https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=app-debug.apk

        # Upload metadata
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -F "file=@build-artifacts/version.txt" \
          https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=version.txt
